version: '3'
services:
  postgres:
    image: postgres:11
    environment:
        POSGRES_DB: app
        POSTGRES_PASSWORD: admin
    ports: 
      - 5433:5432
    privileged: true
    volumes:
      - ./data:/var/lib/postgresql/data
